---
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - openbsd
      - solaris
checksum:
  name_template: 'checksums.txt'
